# Schema for the configuration files of the mtcaptcha module.

mtcaptcha.settings:
  type: config_object
  label: 'mtcaptcha settings'
  mapping:
    site_key:
      type: string
      label: 'Site Key'
    private_key:
      type: string
      label: 'Private Key'
    mtcaptcha_show_captcha_label_form:
      type: string
      label: 'Show Captcha label in the form'
    theme:
      type: string
      label: 'Theme'
    language:
      type: string
      label: 'Language'
    widgetsize:
      type: string
      label: 'Captcha Widget Size'
    enablecaptcha:
      type: string
      label: 'Enable MTCaptcha for'
    other_form_id:
      type: array
      label: 'Other Forms to enable'
    form_enable:
      type: array
      label: 'MTCaptcha is applied for'
    custom_config_enable:
      type: string
      label: 'Enable custom MTCaptcha configuration'
    custom_config_enable: 
      type: string
      label: 'Custom MTCaptcha configuration'
