# Schema for the configuration files of the mtcaptcha module.

mtcaptcha.settings:
  type: config_object
  label: 'mtcaptcha settings'
  mapping:
    site_key:
      type: string
      label: 'Site Key'
    private_key:
      type: string
      label: 'Private Key'
      type: mapping
      label: 'Widget settings'
      mapping:
        theme:
          type: string
          label: 'Theme'
        language:
          type: string
          label: 'Language'
        widgetsize:
          type: string
          label: 'Captcha Widget Size'
        enablecaptcha:
          type: string
          label: 'Enable MTCaptcha for'
        type:
          type: string
          label: 'Type'
        size:
          type: string
          label: 'Size'
        tabindex:
          type: integer
          label: 'Tabindex'
        noscript:
          type: boolean
          label: 'Enable fallback for browsers with JavaScript disabled'
        lgin_form:
          type: boolean
          label: 'Login Form'
        registration_form:
          type: boolean
          label: 'Registeration Form'
        lost_password_form:
          type: boolean
          label: 'Lost Password Form'
        change_password_form:
          type: boolean
          label: 'Change Password Form'
        comment_form:
          type: boolean
          label: 'Comment Form'
        contact_form:
          type: boolean
          label: 'Contact Form'
